name: "Common Pentaho Maven Settings file"
description: "Common Pentaho Maven Settings file"

outputs:
  settings-file-path:
    description: "Maven settings file path"
    value: ${{ steps.settings-file.outputs.path }}

runs:
  using: "composite"
  steps:

    - name: Checkout code
      if: ${{ env.run_plugin_integration_tests == '' }}
      uses: actions/checkout@v4

    - name: Return settings.xml
      id: settings-file
      shell: sh
      run: |
        file_path="$GITHUB_ACTION_PATH/settings.xml"
        
        echo "path=${file_path}" >> $GITHUB_OUTPUT

    # TODO - move this into the github actions image
    - name: Configure vm.max_map_count required by Elasticsearch
      if: ${{ env.run_plugin_integration_tests }}
      shell: bash
      run: |
        echo "vm.max_map_count=262144" >> /etc/sysctl.conf
